---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: boshcpi/openstack-cpi-release

inputs:
- name: validator-src-in
- name: bosh-openstack-cpi-release

outputs:
- name: validator-src-cpi-bumped

run:
  path: validator-src-in/ci/tasks/bump-openstack-cpi.sh
